name: CI

on:
  push:
    branches: [ main, release/v* ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    branches: [ main, release/v* ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_call:
    inputs:
      release:
        required: false
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
          8.0.x

    - name: Restore Tools
      run: dotnet tool restore

    - name: Calc Version
      run: dotnet gitversion /updateprojectfiles /output buildserver

    - name: Build
      run: dotnet build -c Release

    - name: Pack
      if: ${{ inputs.release }}
      run: dotnet pack -c Release --no-build

    - uses: actions/upload-artifact@v3
      if: ${{ inputs.release }}
      with:
        name: artifacts
        path: ./artifacts/package/release/*
